### PR TITLE
s/fun/function/

### PR DESCRIPTION
**Pull request by tiagopog**
Today I went through an error where I got the following message:

```
lib/ziad_ex/payload.ex:44:no_return
The created fun has no local return.
```

I've got the meaning of `fun` by the context, I think it's worth making it a bit clearer though.

BTW, thanks for this awesome lib :-)

### CODE REVIEW

**Comment by jeremyjh** [comment]
I think what we are after with `fun` is that it's an anonymous function, but this is Erlang terminology. Personally I think `fn` would be more clear, but maybe we should just say `anonymous function`. Thoughts @asummers ?

**Comment by asummers** [comment]
In this case, it's exactly anonymous function. But I'm fine with either verbiage -- either yours or the one currently in PR. This message is derived from the original Erlang messaging and hasn't gotten an editor's hand yet, apparently.

**Comment by jeremyjh** [comment]
@tiagopog do you mind updating to say `anonymous function` ?

**Comment by jeremyjh** [comment]
Thanks!

**Pull request merged**
