### PR TITLE
support --halt-exit-status option

### PR DESCRIPTION
**Pull request by schnittchen**
This implements #33. I could not find a way for dialyzer to exit with status 1, so I could check only 0 and 2.

### CODE REVIEW

**Comment by jeremyjh** [comment]
Hi, Thanks! 

A suggestion, perhaps we should check if exit status equals 0, and exit normally if so. That way if you are chaining mixing commands it only halts on a dialyzer issue.

Also could you please update the @moduledoc to describe the new argument, and bump the version in mix.exs?

**Comment by schnittchen** [comment]
When the new option is used, I'd expect the exit status to be exactly the same as dialyzer's. That is no longer the case when chaining is possible.

I would rather keep the code as is and document that behaviour.

**Comment by jeremyjh** [comment]
Ok thats fine, I agree just point that out in the doc string.

**Comment by schnittchen** [comment]
Commits added.

**Comment by jeremyjh** [comment]
Thanks, if you'll just squash the commits I will merge. You can do this with a rebase -i and fixup the second two commits then push it with a -f flag.

**Comment by schnittchen** [comment]
Done.

**Comment by jeremyjh** [comment]
Thanks!

**Pull request merged**
