### PR TITLE
Fixed an issue related to missing optional applications

### PR DESCRIPTION
**Pull request by GRoguelon**
The PR updates the deps_app/2 function in the Dialyxir.Project module in `lib/dialyxir/project.ex` to handle different versions of Elixir. Added version checking for Elixir 1.15 or later, and adjusted the implementation accordingly. The changes ensure that the `deps_app/2` function works correctly with the appropriate version of Elixir.

I'm not totally sure if my change is backward compatible with previous versions of Elixir. Also not sure if there is a better option to avoid the version check.

I used this patch for an Elixir/Phoenix application on 1.15 for several weeks without any issues and no warnings about optional applications.

Closes #509

### CODE REVIEW

**Comment by axelson** [comment]
Thanks for this! I tested it on a work repository and it works as advertised :+1:

This should be marked as Fixes https://github.com/jeremyjh/dialyxir/issues/502 as well.

**Review by jeremyjh — APPROVED** [review]

**Comment by jeremyjh** [comment]
Thanks!

**Comment by whatyouhide** [comment]
@jeremyjh @GRoguelon this inadvertently bumps the Elixir requirement to 1.14+ because it uses `then/2`. @GRoguelon maybe you wanna send a PR that doesn't use `then/2`, so that this stays compatible with Elixir 1.6+, like `mix.exs` declares? 🙃

**Comment by whatyouhide** [comment]
@jeremyjh what I’m saying is that if the library is **only** compatible with Elixir 1.15+, then we should change the requirement in `mix.exs` ([here](https://github.com/jeremyjh/dialyxir/blob/7285f152418def3dd28c318f49613054f3c7e788/mix.exs#L11)) to `~> 1.12`. I see that you did that on the main branch, but the problem is that the 1.4.0 release [declares it supports `1.6+`](https://preview.hex.pm/preview/dialyxir/1.4.0/show/mix.exs#L11), but it uses [`then/2`](https://hexdocs.pm/elixir/Kernel.html#then/2), which was released in Elixir 1.12.

So right now it might be just a matter of releasing 1.4.1 as a bug fix 😉

**Comment by jeremyjh** [comment]
I released 1.4.1 last night.

**Comment by bryannaegele** [comment]
It would be nice if the change could be updated to not use `then` as while this project may only be testing 3 versions back, we have to support back further for some major libraries as we base off of supported OTP version rather than Elixir. We still have to support back to 1.11 for another year (OTP 27).

**Comment by David-Klemenc** [comment]
Something like this:

```
== Compilation error in file lib/dialyxir/project.ex ==
Error: ** (CompileError) lib/dialyxir/project.ex:365: undefined function then/2
```

```elixir
  @spec check_version(Version.t()) :: boolean()
  defp check_version(%Version{major: major, minor: minor}) do
    major >= 1 and minor >= 15
  end

  if System.version() |> Version.parse!() |> check_version() do
```

**Comment by David-Klemenc** [comment]
Something like this:

```
== Compilation error in file lib/dialyxir/project.ex ==
Error: ** (CompileError) lib/dialyxir/project.ex:365: undefined function then/2
```

```elixir
if System.version() |> Version.parse!() |> (&(&1.major >= 1 and &1.minor >= 15)).() do
```

**Pull request merged**
