### PR TITLE
Added dialyxir.clean task

### PR DESCRIPTION
**Pull request by gnufede**
Added `mix dialyxir.clean` task that deletes PLT and hash files.

Added a new parameter to `find_plts` function, with the function to be called
on the PLTs found.

Solves [https://github.com/jeremyjh/dialyxir/issues/107](https://github.com/jeremyjh/dialyxir/issues/107)

### CODE REVIEW

**Comment by jeremyjh** [comment]
I think this looks good but we also need to add docs so that something is displayed for the task in `mix help` as well as `mix help dialyzer.clean`.  Also this is probably pretty testable - could you look at also adding tests for this as well please?

**Comment by jeremyjh** [comment]
Hi, sorry I neglected reviewing this further until now. I took a look and everything you have looks fine, but re-reading #107 again I'm left with the impression it was also requesting the core plts (in MIX_HOME) would be deleted. I'm not sure why that would be necessary though -  @christhekeele can you clarify if that was the original ask, and if so what benefit it would provide?

**Comment by christhekeele** [comment]
That was the original ask—though I think the partial purge might be useful to someone, perhaps as a flag.

What I was requesting is the ability to fully unwind any artifacts produced by `mix dialyzer` tasks, without having to know where it stores them. This is to serve the same purpose as `mix deps.clean` and `mix clean`: to blow away all state so you know that `mix xxx.build` starts with a fresh state.

The reasoning is that while common usecase won't need this, if you're wrangling CI environments or trying to build PLTs in advance, you're probably doing something bespoke enough that you want full control over all files the task touches.

**Comment by jeremyjh** [comment]
@christhekeele the difference to `mix deps.clean` or `mix clean` is that their scope is limited to the current project directory. Deleting shared files in MIX_HOME might not be the first thing you'd expect from this task, it would seem like that would be safer to put behind an `--all` flag.

**Comment by christhekeele** [comment]
I agree that an `--all` flag makes sense for this, and has nice parity with similar tasks (`mix deps.clean --all` for instance).

**Comment by gnufede** [comment]
Agreed, I'll make the changes so it'll only delete core plts if `--all` flag is set

**Comment by gnufede** [comment]
I think it's ready now @jeremyjh, I hope you like the approach.

**Comment by jeremyjh** [comment]
Looks great, thanks @gnufede !

**Pull request merged**
