### PR TITLE
Support a "Quiet" Option

### LINKED ISSUE #85: Passing command line arguments does not work
Version 0.5.0

```elixir
  def project do
    [
      ...
      dialyzer: [
        plt_add_deps: :transitive,
        ignore_warnings: "dialyzer.ignore-warnings",
        flags: ["--quiet"]
      ]
    ]
  end
```

Running:

```shell
mix dialyzer
Compiling 23 files (.ex)
Generated efrontback app
Checking PLT...
[skipped]
PLT is up to date!
Starting Dialyzer
dialyzer args: [check_plt: false,
 init_plt: 'skipped',
 files_rec: ['skipped'],
 warnings: [:quiet, :unknown]]
:dialyzer.run error: Unknown dialyzer warning option: quiet
```

The docs say: _You can specify any `dialyzer` command line argument with the :flags keyword._

Am I missing anything?

### PR DESCRIPTION
**Pull request by jeremyjh**
This will resolve #85 .

Also resolves #111.

### CODE REVIEW

**Comment by jeremyjh** [comment]
@asummers I added some notes about upgrading to 1.0: https://github.com/jeremyjh/dialyxir/pull/100/files#diff-04c6e90faac2675aa89e2176d2eec7d8R7

Anything else we should say there?

**Comment by asummers** [comment]
Previous ignore files are still compatible. There's a filter_legacy pass that calls the dialyzer formatting and does the relevant logic. Should just be plug and play unless you want to use the new format.

**Comment by jeremyjh** [comment]
Excellent, thanks!

**Comment by asummers** [comment]
I would say to do an RC release first too, so that we can get any remaining bugs/feature requests like the one opened last night and the one being asked about in the Elixir Forum thread. Shoot out a thing to the ElixitStatus weekly newsletter thing as a project update, then let it simmer for like 2 weeks, maybe?

**Comment by jeremyjh** [comment]
Sure, good idea.

**Pull request merged**
