### PR TITLE
Add plt_ignore_apps option to ignore dependencies

### LINKED ISSUE #295: Add a `plt_ignore_app(s)` option
### Current behavior

Some apps ([Saxy is an example](https://github.com/qcam/saxy/issues/39)) take a very large amount of time to pass the dialyzer for certain versions of OTP. If we can pinpoint which dependency takes so long, we should be able to ignore only that dependency.

Currently if I want to ignore a single dependency, I need to make a configuration that looks like this:

```elixir
   # mix.exs, project section
  ...
  dialyzer: [
    ignore_warnings: ".dialyzer_ignore.exs",
    plt_apps: [
      :erts,
      :kernel,
      :stdlib,
      ... # all other dependencies except the one that hangs
    ]
  ]
```

### Expected behavior

I'd like to be able to just say the app I'd like to ignore:

```elixir
   # mix.exs, project section
  ...
  dialyzer: [
    ignore_warnings: ".dialyzer_ignore.exs",
    plt_ignore_apps: [:saxy]
  ]
```

I imagine that there's an easy place to put a `plt_apps -- ignored_apps` in the setup. If you like the idea, I'd be happy to send in a PR

### PR DESCRIPTION
**Pull request by the-mikedavis**
Closes #295.

The documentation will need a small change as well. I'll leave that to you

### CODE REVIEW

**Comment by asummers** [comment]
I think this looks fine. Maybe missing some tests but there's not much of a harness around that section. 

@jeremyjh what kinda docs do you think we want for this?

**Comment by jeremyjh** [comment]
I think it just needs to be mentioned in the README and module docs next to the other PLT options. It definitely can be tested using the mocks and helpers in project_test.

**Comment by gilacost** [comment]
Can we please update this and merge  🙏

**Comment by the-mikedavis** [comment]
Hey @jeremyjh, when you have a moment, take another look at this and let me know if I can improve anything

**Comment by jeremyjh** [comment]
Thanks!

**Pull request merged**
