### PR TITLE
Do not load optional applications

### LINKED ISSUE #502: Dialyxir attempts to load transitive optional dependencies
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.15.0-rc.0, OTP 26.0

* Which version of Dialyxir are you using? (cat mix.lock | grep dialyxir): 1.3.0

### Current behavior

Dialyxir is issuing warnings that it can't load applications that are transitive optional dependencies. An example using the [ex_cldr](https://github.com/elixir-cldr/cldr) lib:
```elixir
kip@Kips-MacBook-Pro cldr % asdf current
elixir          1.15.0-rc.0-otp-26 /Users/kip/Development/cldr/.tool-versions
erlang          26.0            /Users/kip/Development/cldr/.tool-versions
rust            stable          /Users/kip/.tool-versions
kip@Kips-MacBook-Pro cldr % mix dialyzer
Finding suitable PLTs
Checking PLT...
Error loading castore, dependency list may be incomplete.
 {~c"no such file or directory", ~c"castore.app"}
Error loading certifi, dependency list may be incomplete.
 {~c"no such file or directory", ~c"certifi.app"}
[:asn1, :castore, :certifi, :cldr_utils, :compiler, :crypto, :decimal, :earmark_parser, :eex, :elixir, :ex_doc, :ex_unit, :expo, :gettext, :inets, :jason, :kernel, :logger, :makeup, :makeup_elixir, :makeup_erlang, :mix, :nimble_parsec, :public_key, :ssl, :stdlib, :sweet_xml, :xmerl]
PLT is up to date!
ignore_warnings: .dialyzer_ignore_warnings

Starting Dialyzer
[
  check_plt: false,
  init_plt: ~c"/Users/kip/Development/cldr/_build/dev/dialyxir_erlang-26.0_elixir-1.15.0-rc.0_deps-dev.plt",
  files: [~c"/Users/kip/Development/cldr/_build/dev/lib/ex_cldr/ebin/Elixir.Cldr.LanguageTag.Chars.Cldr.LanguageTag.U.beam",
   ~c"/Users/kip/Development/cldr/_build/dev/lib/ex_cldr/ebin/Elixir.Cldr.Normalize.CalendarEra.beam",
   ~c"/Users/kip/Development/cldr/_build/dev/lib/ex_cldr/ebin/Elixir.Cldr.NoParentError.beam",
   ~c"/Users/kip/Development/cldr/_build/dev/lib/ex_cldr/ebin/Elixir.Cldr.UnknownFormatError.beam",
   ~c"/Users/kip/Development/cldr/_build/dev/lib/ex_cldr/ebin/Elixir.Mix.Tasks.Cldr.Install.Locales.beam",
   ...],
  warnings: [:unknown]
]
Total errors: 0, Skipped: 0, Unnecessary Skips: 0
done in 0m14.38s
done (passed successfully)
```
The libs `:castore` and `:certifi` are optional dependencies of [cldr_utils](https://github.com/elixir-cldr/cldr_utils). `cldr_utils` is a required dependency of `ex_cldr`.

The warning messages are unique to Elixir 1.15 / OTP 26.  

I don’t see this output for any other combinations I’ve tried:

* Elixir 1.15.0-rc.0-otp-25 with Erlang 25.3.2
* Elixir 1.14.4-otp-26 with Erlang 26.0
* Elixir 1.14.4-otp-25 with Erlang 25.3.2

Per [this comment](https://elixirforum.com/t/elixir-v1-15-0-rc-0-released/56019/27) it seems reasonable that the addition of an `optional_dependencies` config key to `.app` files in OTP 24 and now the building of that config key in Elixir 1.15 may be part of the issue.  The relevant code in dialyxir seems to be: https://github.com/jeremyjh/dialyxir/blob/e9556460bc130287dd6687ab02041634ac827913/lib/dialyxir/project.ex#L383

### Expected behavior

No warnings are issues when attempting to load transitive optional dependencies.

### PR DESCRIPTION
**Pull request by aptinio**
Thanks to @josevalim's explanation:
https://elixirforum.com/t/elixir-v1-15-0-rc-0-released/56019/27

Fixes #502.

### CODE REVIEW

**Comment by josevalim** [comment]
Unfortunately this is not correct. You don't want to delete all optional applications, you still want to load them. Instead, you want to not report them in case they cannot load.

**Comment by aptinio** [comment]
@josevalim, you got me thinking... so I tested it out to make sure. The computed `deps_apps` in the project I'm working on are the same on Elixir 1.14 without this PR and on Elixir 1.15 with this PR.

Since `deps_apps/2` is being called recursively, the optional deps that are explicitly installed still get included in the first call to `deps_apps`.

Also, as far as I can tell, this PR is replicating the old behavior that you mentioned in https://elixirforum.com/t/elixir-v1-15-0-rc-0-released/56019/27:

> In earlier Elixir versions, foo.app would look like this if gettext was not added as dependency somewhere:
> 
> ```erlang
> {applications, []}
> ```
> 
> But now it looks like this:
> 
> ```erlang
> {optional_applications, [gettext]}
> {applications, [gettext]}
> ```

What do you think? Thanks for looking into this! :relaxed:

**Comment by josevalim** [comment]
This will be true because you don't use gettext. But someone may use gettext, and now it will be removed, while it should have been listed.

**Comment by GRoguelon** [comment]
@josevalim I made a proposal on @aptinio 's repo: https://github.com/aptinio/dialyxir/pull/1

**Comment by GRoguelon** [comment]
Hi @jeremyjh,

I've submitted a [PR](https://github.com/aptinio/dialyxir/pull/1) for the issue related to `Unknown application` with optional applications. Should I create a new PR directly in this repo?

Thank you.

**Comment by jeremyjh** [comment]
@GRoguelon yes please make a new PR on this repo and we'll close this one.

**Comment by GRoguelon** [comment]
@jeremyjh Done: #514

**Pull request closed without merging**
